# Generated by Django 4.2.12 on 2024-07-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EthereumTransaction',
            fields=[
                ('block_number', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('hash', models.CharField(max_length=66, primary_key=True, serialize=False)),
                ('nonce', models.BigIntegerField()),
                ('block_hash', models.CharField(max_length=66)),
                ('transaction_index', models.IntegerField()),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('value', models.BigIntegerField()),
                ('gas', models.BigIntegerField()),
                ('gas_price', models.BigIntegerField()),
                ('is_error', models.IntegerField()),
                ('txreceipt_status', models.IntegerField(blank=True, null=True)),
                ('input', models.TextField()),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('cumulative_gas_used', models.BigIntegerField()),
                ('gas_used', models.BigIntegerField()),
                ('confirmations', models.BigIntegerField()),
                ('method_id', models.CharField(max_length=10)),
                ('function_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=42)),
            ],
            options={
                'db_table': 'dev_crypto_tracker"."ethereum_transaction',
            },
        ),
    ]
