# Generated by Django 4.2.12 on 2024-07-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumtransaction',
            name='value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
