# Generated by Django 4.2.12 on 2024-07-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0002_alter_ethereumtransaction_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumtransaction',
            name='function_name',
            field=models.CharField(max_length=1024),
        ),
    ]
