# Generated by Django 4.2.12 on 2024-07-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0004_erc20transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ERC20Transaction',
        ),
    ]
