# Generated by Django 4.2.12 on 2024-07-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0005_delete_erc20transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ERC20Transaction',
            fields=[
                ('composite_id', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('block_number', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('hash', models.CharField(max_length=66)),
                ('nonce', models.BigIntegerField()),
                ('block_hash', models.CharField(max_length=66)),
                ('from_address', models.CharField(max_length=42)),
                ('contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('to_address', models.CharField(max_length=42)),
                ('value', models.BigIntegerField(blank=True, null=True)),
                ('token_name', models.CharField(max_length=1024)),
                ('token_decimal', models.IntegerField()),
                ('transaction_index', models.IntegerField()),
                ('gas', models.BigIntegerField()),
                ('gas_price', models.BigIntegerField()),
                ('gas_used', models.BigIntegerField()),
                ('cumulative_gas_used', models.BigIntegerField()),
                ('input', models.TextField()),
                ('confirmations', models.CharField(max_length=66)),
                ('address', models.CharField(max_length=42)),
            ],
            options={
                'db_table': 'dev_crypto_tracker"."erc20_transaction',
            },
        ),
    ]
