# Generated by Django 4.2.12 on 2024-07-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0006_erc20transaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='erc20transaction',
            unique_together={('hash', 'from_address', 'to_address')},
        ),
    ]
