# Generated by Django 4.2.12 on 2024-07-28 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0007_alter_erc20transaction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='erc20transaction',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 11, 31, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='ethereumtransaction',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 11, 31, tzinfo=datetime.timezone.utc)),
        ),
    ]
