# Generated by Django 4.2.12 on 2024-07-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0009_erc20transaction_erc20_trans_from_ad_f43ba7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='erc20transaction',
            name='erc20_trans_from_ad_f43ba7_idx',
        ),
        migrations.RemoveIndex(
            model_name='erc20transaction',
            name='erc20_trans_to_addr_8d5cbf_idx',
        ),
        migrations.RemoveIndex(
            model_name='erc20transaction',
            name='erc20_trans_from_ad_c424d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='ethereumtransaction',
            name='ethereum_tr_from_ad_978688_idx',
        ),
        migrations.RemoveIndex(
            model_name='ethereumtransaction',
            name='ethereum_tr_to_addr_286606_idx',
        ),
        migrations.RemoveIndex(
            model_name='ethereumtransaction',
            name='ethereum_tr_from_ad_1c65e6_idx',
        ),
        migrations.AddIndex(
            model_name='erc20transaction',
            index=models.Index(fields=['address'], name='erc20_trans_address_fc5fee_idx'),
        ),
        migrations.AddIndex(
            model_name='erc20transaction',
            index=models.Index(fields=['block_number'], name='erc20_trans_block_n_2873ba_idx'),
        ),
        migrations.AddIndex(
            model_name='ethereumtransaction',
            index=models.Index(fields=['address'], name='ethereum_tr_address_2eea31_idx'),
        ),
        migrations.AddIndex(
            model_name='ethereumtransaction',
            index=models.Index(fields=['block_number'], name='ethereum_tr_block_n_38775c_idx'),
        ),
    ]
