# Generated by Django 4.2.12 on 2024-07-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0010_remove_erc20transaction_erc20_trans_from_ad_f43ba7_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='erc20transaction',
            index=models.Index(fields=['from_address'], name='erc20_trans_from_ad_f43ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='erc20transaction',
            index=models.Index(fields=['to_address'], name='erc20_trans_to_addr_8d5cbf_idx'),
        ),
        migrations.AddIndex(
            model_name='erc20transaction',
            index=models.Index(fields=['from_address', 'to_address'], name='erc20_trans_from_ad_c424d8_idx'),
        ),
        migrations.AddIndex(
            model_name='ethereumtransaction',
            index=models.Index(fields=['from_address'], name='ethereum_tr_from_ad_978688_idx'),
        ),
        migrations.AddIndex(
            model_name='ethereumtransaction',
            index=models.Index(fields=['to_address'], name='ethereum_tr_to_addr_286606_idx'),
        ),
        migrations.AddIndex(
            model_name='ethereumtransaction',
            index=models.Index(fields=['from_address', 'to_address'], name='ethereum_tr_from_ad_1c65e6_idx'),
        ),
    ]
