# Generated by Django 4.2.12 on 2024-07-29 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0011_erc20transaction_erc20_trans_from_ad_f43ba7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('believed_illicit', models.BooleanField(default=False)),
                ('confirmed_illicit', models.BooleanField(default=False)),
                ('believed_crime', models.CharField(blank=True, max_length=255, null=True)),
                ('total_sent_transactions', models.IntegerField(default=0)),
                ('total_received_transactions', models.IntegerField(default=0)),
                ('unique_sent_addresses', models.IntegerField(default=0)),
                ('unique_received_addresses', models.IntegerField(default=0)),
                ('total_ether_sent', models.DecimalField(decimal_places=18, default=0, max_digits=30)),
                ('total_ether_received', models.DecimalField(decimal_places=18, default=0, max_digits=30)),
                ('total_erc20_sent', models.DecimalField(decimal_places=18, default=0, max_digits=30)),
                ('total_erc20_received', models.DecimalField(decimal_places=18, default=0, max_digits=30)),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2021, 5, 26, 11, 31, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'db_table': 'dev_crypto_tracker"."wallet',
                'indexes': [models.Index(fields=['address'], name='wallet_address_7130a3_idx'), models.Index(fields=['owner'], name='wallet_owner_2cd6c8_idx'), models.Index(fields=['believed_illicit'], name='wallet_believe_bc7255_idx'), models.Index(fields=['confirmed_illicit'], name='wallet_confirm_6591ce_idx')],
            },
        ),
    ]
