# Generated by Django 4.2.12 on 2024-08-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0013_role_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='believed_count',
            field=models.IntegerField(default=0),
        ),
    ]
