# Generated by Django 4.2.12 on 2024-08-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0018_walletnote_note_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True),
        ),
    ]
