# Generated by Django 4.2.12 on 2024-09-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webview', '0019_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletanalysis',
            name='analysis_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
