FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt /app/

# Install any dependencies
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app/

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run Django development server
CMD ["bash", "-c", "python manage.py migrate && python manage.py createsuperuser_if_none && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"]
