version: '3.8'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/webview
      - ./static:/webview/static
      - ./media:/webview/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin  # Replace with your desired username
      - DJANGO_SUPERUSER_EMAIL=admin@example.com  # Replace with your desired email
      - DJANGO_SUPERUSER_PASSWORD=X1B2#WXYZ123a  # Replace with your desired password
      - DATABASE_NAME=CryptoTracker
      - DATABASE_USER=crypto-postgres
      - DATABASE_PASSWORD=X1B2#WXYZ123a
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - ETHERSCAN_API_KEY=RNT7YF8V9S21MYZCWFF2ICW235EAME6XT8
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: CryptoTracker
      POSTGRES_USER: crypto-postgres
      POSTGRES_PASSWORD: X1B2#WXYZ123a
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the SQL script

volumes:
  postgres_data:
