# This Docker Compose file provisions a local development environment tailored for testing application releases.

version: "3.9"
services:
  # Seq: Provides structured logging. Accessible at http://localhost:5341/
  seq:
    image: "datalust/seq:latest"
    ports: 
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
  
  # Zipkin: Offers distributed tracing. After starting, visit http://localhost:9411/zipkin/ and click 'run query' to view traces
  zipkin:
    image: "openzipkin/zipkin-slim"
    ports:
      - 9411:9411

  # Prometheus: System monitoring and alerting. Accessible at http://localhost:9090/
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    
  # Grafana: Interactive visualization and analytics platform. Accessible at http://localhost:3000/ Login using the username: admin Passowrd: admin / password
  grafana:
    image: grafana/grafana:8.0.6
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  # crytpo-analysis-ui: The primary endpoint is http://localhost:5001. Health status can be checked at http://localhost:5001/health. Metrics can be checked at http://localhost:5001/metrics
  crytpo-analysis-ui:
    build: 
      context: ../Application Code
      dockerfile: ##
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_URLS=http://*:8080
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - SeqEndpoint=http://seq:80
      - Serilog__WriteTo__2__Name=Seq
      - Serilog__WriteTo__2__Args__ServerUrl=http://seq:80
      - Serilog__WriteTo__2__Args__RestrictedToMinimumLevel=Debug
    depends_on:
      - "zipkin"
      - "seq"

  # crytpo-analysis-backend: The primary endpoint is http://localhost:5050/. Health status can be checked at http://localhost:5050/health. Metrics can be checked at http://localhost:5050/metrics
  crytpo-analysis-backend:
    build: 
      context: ../Application Code
      dockerfile: ##
    ports:
      - "5050:8080"
    environment:
      - ASPNETCORE_URLS=http://*:8080
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - SeqEndpoint=http://seq:80
      - Serilog__WriteTo__2__Name=Seq
      - Serilog__WriteTo__2__Args__ServerUrl=http://seq:80
      - Serilog__WriteTo__2__Args__RestrictedToMinimumLevel=Debug
    depends_on:
      - "zipkin"
      - "seq"

volumes:
  prometheus_data:
  grafana-storage: